[package]
name = "ce-sign"
edition = "2021"
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags.workspace = true
ce-core.workspace = true
gcl.workspace = true
indexmap.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
stdx.workspace = true
tapi.workspace = true
tracing.workspace = true
